baseURL = "https://www.aepps.com/"
languageCode = "en-us"
title = "aeternity aepps Portal"

[[menu.main]]
	url='/'
	name='æpp portal'
	weight = -111

[[menu.footer]]
	url='https://www.aeternity.com/'
	name= "æternity.com"
[[menu.footer]]
	url='/get-started-with-ae'
	name= "Get started Guide"
[[menu.footer]]
	url='https://blog.aeternity.com/'
	name= "æternity on Medium"
